spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/item_administraion_system
    username: postgres
    password: postgres
server:
  servlet:
    context-path: /itemadministration